/**
 * Google Gemini API integration for image generation
 * Uses Nano Banana Pro (gemini-3-pro-image-preview) model
 */

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta/models';
// Nano Banana Pro - highest quality image generation
const IMAGE_MODEL = 'gemini-3-pro-image-preview';

interface GeminiImageResult {
  url: string; // Base64 data URL
  mimeType: string;
}

/**
 * Generate an image using Gemini's Nano Banana Pro model
 */
export async function generateImageWithGemini(prompt: string): Promise<GeminiImageResult> {
  const apiKey = import.meta.env.GEMINI_API_KEY;

  if (!apiKey || apiKey === 'your-gemini-api-key-here') {
    throw new Error('GEMINI_API_KEY environment variable is not set. Get your key at https://aistudio.google.com/apikey');
  }

  const endpoint = `${GEMINI_API_BASE}/${IMAGE_MODEL}:generateContent`;

  // Add aspect ratio instruction to the prompt itself for reliability
  const enhancedPrompt = `${prompt}\n\nGenerate this as a wide landscape image (16:9 aspect ratio).`;

  const requestBody = {
    contents: [
      {
        parts: [
          {
            text: enhancedPrompt
          }
        ]
      }
    ],
    generationConfig: {
      responseModalities: ['IMAGE', 'TEXT']
    }
  };

  console.log('Gemini request to model:', IMAGE_MODEL);
  console.log('Gemini request body:', JSON.stringify(requestBody, null, 2));

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-goog-api-key': apiKey
    },
    body: JSON.stringify(requestBody)
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    const errorMessage = errorData?.error?.message || response.statusText;
    const errorStatus = errorData?.error?.status || '';

    console.error('Gemini API error:', JSON.stringify(errorData, null, 2));

    if (response.status === 400 || errorStatus === 'INVALID_ARGUMENT') {
      throw new Error(`Gemini rejected the prompt: ${errorMessage}`);
    }
    if (response.status === 401 || response.status === 403) {
      throw new Error('Invalid Gemini API key. Check your GEMINI_API_KEY in .env');
    }
    if (response.status === 429) {
      throw new Error('Gemini rate limit exceeded. Please wait and try again.');
    }

    throw new Error(`Gemini API error (${response.status}): ${errorMessage}`);
  }

  const data = await response.json();

  console.log('Gemini response structure:', JSON.stringify(data, null, 2).substring(0, 1000));

  // Check for blocked content
  if (data.promptFeedback?.blockReason) {
    throw new Error(`Content blocked: ${data.promptFeedback.blockReason}. Try a different prompt.`);
  }

  // Extract the image from the response
  const candidates = data.candidates;
  if (!candidates || candidates.length === 0) {
    // Check if there's a safety rating issue
    if (data.candidates?.[0]?.finishReason === 'SAFETY') {
      throw new Error('Image blocked by safety filters. Try a more generic prompt.');
    }
    throw new Error('No image generated by Gemini. The model may not have produced an image for this prompt.');
  }

  // Check finish reason
  const finishReason = candidates[0]?.finishReason;
  if (finishReason === 'SAFETY') {
    throw new Error('Image blocked by safety filters. Try a more generic prompt.');
  }

  const parts = candidates[0]?.content?.parts;
  if (!parts || parts.length === 0) {
    throw new Error('Invalid response structure from Gemini - no parts in response');
  }

  // Find the image part (inlineData with image mimeType)
  const imagePart = parts.find((part: any) => part.inlineData?.mimeType?.startsWith('image/'));

  if (!imagePart?.inlineData) {
    // Maybe it returned text instead of an image
    const textPart = parts.find((part: any) => part.text);
    if (textPart) {
      console.log('Gemini returned text instead of image:', textPart.text);
    }
    throw new Error('No image data in Gemini response - model may have returned text instead');
  }

  const { mimeType, data: base64Data } = imagePart.inlineData;

  // Return as data URL for preview
  return {
    url: `data:${mimeType};base64,${base64Data}`,
    mimeType
  };
}

/**
 * Save a base64 image to file
 */
export function base64ToBuffer(dataUrl: string): { buffer: Buffer; mimeType: string } {
  const matches = dataUrl.match(/^data:([^;]+);base64,(.+)$/);
  if (!matches) {
    throw new Error('Invalid data URL format');
  }

  const mimeType = matches[1];
  const base64Data = matches[2];
  const buffer = Buffer.from(base64Data, 'base64');

  return { buffer, mimeType };
}
